### ISSUE TITLE
登录页viewmodel无法保存数据

### ISSUE THREAD

**Issue by lizhAndroid** [lilongweidev/MVVM-Demo#2]
请问一下，为什么加上双向绑定后viewmodel无法保存数据，屏幕旋转后数据依然会丢失，看着您的博客写的，安装了您的demo后也是一样的情况

https://user-images.githubusercontent.com/47814979/169970508-5a55472f-eb7b-4405-ab11-6fcde71002d6.mp4

**Comment by lizhAndroid** [comment]
华为荣耀10 ，鸿蒙2.0

**Comment by lilongweidev** [comment]
我的Demo并没有保存数据啊，只不过是输入框输入后数据绑定了，你旋转屏幕后Activity重新创建，ViewModel也会重新绑定，因此没有数据很正常啊，你想要保存数据可以使用Lifecycle。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/MVVM-Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午3:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lilongweidev/MVVM-Demo] 登录页viewmodel无法保存数据 (Issue #2)





 
请问一下，为什么加上双向绑定后viewmodel无法保存数据，屏幕旋转后数据依然会丢失，看着您的博客写的，安装了您的demo后也是一样的情况
 
https://user-images.githubusercontent.com/47814979/169970508-5a55472f-eb7b-4405-ab11-6fcde71002d6.mp4

**Comment by lizhAndroid** [comment]
你前面单向绑定的时候有演示一个数据持久化的，不过好像是重新给model赋值了，我以为是viewmodel自带的持久化，明白了，我后面用你说的Lifecycle试试，谢谢指教

**Comment by lilongweidev** [comment]
Close
